### ISSUE TITLE
The code implementation of eq(7) in the paper

### ISSUE THREAD

**Issue by peiyaoooo** [cnyvfang/CORUN-Colabator#3]
Hi Chengyu,
    Thank you for your good job! I have a question on the code implementation of eq(7).  
    Is the implementation of  eq(7) in the paper corresponding to  the code on line https://github.com/cnyvfang/CORUN-Colabator/blob/main/corun_colabator/archs/corun_arch.py#L292?
    Are they consistent?
    Hope for your reply. Thank you!

**Comment by cnyvfang** [comment]
Of course~ but what might trouble you is that the transpose operation in the formula is at the pixel-wise. Once you understand this, you might be able to better comprehend the consistency between the code and the formulas. (By the way, my name is Chengyu lol.

**Comment by cnyvfang** [comment]
From Line 289 to 299, all of those code is about eq(7).

**Comment by peiyaoooo** [comment]
> Of course~ but what might trouble you is that the transpose operation in the formula is at the pixel-wise. Once you understand this, you might be able to better comprehend the consistency between the code and the formulas. (By the way, my name is Chengyu lol.

Ops!I am so so so so  sorry!!!!!!!!!! I was too careless at that time.  My description was not very clear. 
According to  the latter half of eq(7),  should "factor_1 = (one - p + (self.step_lambda * t_prev / storedValue))"  be in the way of  "factor_1 = (one - p * (self.step_lambda * t_prev / storedValue))? 
But I got the same answer as the code ("factor_1 = (one - p + (self.step_lambda * t_prev / storedValue))" ) according to second equation in your appendix. Is there any typo? I download the paper with arxiv:2406.07966

**Comment by cnyvfang** [comment]
Oh, I quickly checked Eq. (7), and it seems there is indeed a typo. I will review this formula carefully tomorrow and correct the typo in the updated version on arXiv as well as in the final version after the conference. Thank you for pointing it out! If you have any other questions, feel free to add me on WeChat (Chengyu-Fang). Thank you again!
